from decouple import config


MODEL_NAME = config("MODEL_NAME")
OPENAI_API_BASE = config("OPENAI_API_BASE")
USER_ROLE_NAME = config("USER_ROLE_NAME")
ASSISTANT_ROLE_NAME = config("ASSISTANT_ROLE_NAME")

DATABASE_URL = config("DATABASE_URL")
